name: BoostBadge Backend Build Image & Deploy to Docker Hub

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Build and Push to Docker Hub
      run: |
        docker build . --file Dockerfile --tag gberg927/bb-backend-test:latest
        docker login --username=${{ secrets.DOCKER_HUB_USERNAME }} --password=${{ secrets.DOCKER_HUB_PASSWORD }}
        docker push gberg927/bb-backend-test:latest
